export interface IIhtiyacPlanlamaRapor {
    id: number,
    tarih?: Date,
    hucreId:number,
    projeKodu:string,
    projeAciklama?:string,
    plasiyerKodu:string,
    plasiyerAciklama?:string,
    mamulAdi?:string,
    stokKartiId:number,
    stokKodu:string,
    stokAdi?:string,
    miktar:number,
    olcuBirimId:number,
    olcuBirim?:string,
    belgeNo?:string,
    cikisMiktar:number,
    yuruyenIhtiyac:number,
    bakiye:number,
    stokTalepMiktari:number,
    stokSiparisMiktari:number,
    toplamIhtiyac:number,
    yuruyenBakiye:number,
    olcuBrId:number,
    olcuBr:string,
}
