import { IDovizTipi } from "../tanimlamalar/IDovizTipi";
import { IHucreOzet } from "../tanimlamalar/IHucreOzet";
import { IStokOlcuBirim } from "../tanimlamalar/IStokOlcuBirim";
import { IStokKod } from "./IStokKod";

export interface IStok {
  id?: number;
  kodu: string;
  adi: string;
  ingilizceIsim: string;
  stokGrupKoduId: any;
  stokGrupKodu:IStokKod;
  stokKod1Id: number;
  stokKod1:IStokKod;
  stokKod2Id: number;
  stokKod2:IStokKod;
  stokKod3Id: number;
  stokKod3:IStokKod;
  stokKod4Id: number;
  stokKod4:IStokKod;
  stokKod5Id: number;
  stokKod5:IStokKod;
  stokOlcuBirim1Id: number;
  stokOlcuBirim1:IStokOlcuBirim;
  stokOlcuBirim2Id: number;
  stokOlcuBirim2:IStokOlcuBirim;
  olcuBr2Pay: number;
  olcuBr2Payda: number;
  stokOlcuBirim3Id: number;
  stokOlcuBirim3:IStokOlcuBirim;
  olcuBr3Pay: number;
  olcuBr3Payda: number;
  hucreOzets:IHucreOzet[];
  alisDovizTipiId: number;
  alisDovizTipi?:IDovizTipi;
  satisDovizTipiId: number;
  satisDovizTipi?:IDovizTipi;
  alisFiyati: number;
  satisFiyati: number;
  alisKDVOrani: number;
  satisKDVOrani: number;
  seriTakibiVarMi: boolean;
  seriMiktarKadarMi:boolean;
  seriGirisOtomatikMi:boolean;
  en: number;
  boy: number;
  genislik: number;
  agirlik: number;
  asgariStokMiktari: number;
  azamiStokMiktari: number;
  minimumSiparisMiktari: number;
  aktarimDurumu: number;
  bakiye:number;
}
