import { IStokKod } from "./IStokKod";

export interface IStok {
  id?: number;
  kodu: string;
  adi: string;
  ingilizceIsim: string;
  stokGrupKoduId: any;
  stokGrupKodu:IStokKod;
  stokKod1Id: any;
  stokKod1:IStokKod;
  stokKod2Id: any;
  stokKod2:IStokKod;
  stokKod3Id: any;
  stokKod3:IStokKod;
  stokKod4Id: any;
  stokKod4:IStokKod;
  stokKod5Id: any;
  stokKod5:IStokKod;
  stokOlcuBirim1Id: number;
  stokOlcuBirim2Id: any;
  olcuBr2Pay: number;
  olcuBr2Payda: number;
  stokOlcuBirim3Id: any;
  olcuBr3Pay: number;
  olcuBr3Payda: number;
  alisDovizTipiId: number;
  satisDovizTipiId: number;
  alisFiyati: number;
  satisFiyati: number;
  alisKDVOrani: number;
  satisKDVOrani: number;
  seriTakibiVarMi: boolean;
  en: number;
  boy: number;
  genislik: number;
  agirlik: number;
  asgariStokMiktari: number;
  azamiStokMiktari: number;
  minimumSiparisMiktari: number;
  aktarimDurumu: number;
}
